service: siewlee-serverless-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  getapi:
    handler: index.firsthandler
    events:
      - httpApi:
          path: /
          method: get

  postapi:
    handler: index.secondhandler
    events:
      - httpApi:
          path: /post
          method: post

plugins:
  - serverless-offline