service: siewlee-serverless-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  deploymentBucket:
    name: cohort5.deployment

functions:
  getapi:
    handler: index.firsthandler
    events:
      - httpApi:
          path: /
          method: get
      - sqs:
          arn: arn:aws:sqs:us-east-1:255945442255:siewlee-sqs-serverless

  postapi:
    handler: index.secondhandler
    events:
      - httpApi:
          path: /post
          method: post
      - sqs:
          arn:
            Fn::GetAtt:
              - siewleequeue
              - Arn

resources:
  Resources:
    siewleequeue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "siewlee-queue-serverless"

plugins:
  - serverless-offline